version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./internal/static/
builds:
  -
    id: glmo-darwin
    binary: glmo
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/k1LoW/mo/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  -
    id: glmo-windows
    binary: glmo
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/k1LoW/mo/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
  -
    id: glmo-linux
    binary: glmo
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/k1LoW/mo/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  -
    id: glmo-archive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: darwin
        formats:
          - zip
    files:
      - LICENSE
      - CREDITS
      - README.md
      - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: glmo-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    ids:
      - glmo-linux
    homepage: https://github.com/aXisho/cuemo
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: "glmo is a Gloss Markdown viewer that opens .md and .gloss.md files in a browser"
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
release:
  use_existing_draft: true
